name: Simple git push action
description: Push GitHub action output into your repository
author: jasineri
inputs:
  repo_token:
    description: A token to authenticate on behalf of the GitHub App installed on your repository
    required: true
  directory:
    description: Outputs/source directory
    required: false
    default: dist
runs:
  using: composite
  steps:
    #        git config --global user.name "github-actions[bot]"
    #        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: |
        cd ${{ inputs.directory }}
        git add -A
        git commit -m "update action output"
        git push
      shell: bash
    #      env:
    #        GITHUB_TOKEN: ${{ inputs.repo_token }}